import styles from './page.module.scss';

export const metadata = {
  title: 'Bliss | About Us',
  description: 'Generated by create next app',
};

export default function AboutPage() {
  return (
    <main>
      <div className={styles.aboutSection}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam
        ullamcorper euismod libero, sed scelerisque justo consectetur non. Sed
        nec massa nec turpis vestibulum convallis eu a leo. Nullam scelerisque
        nec massa a venenatis. Vivamus commodo ligula in nunc mattis, id
        vestibulum justo interdum. Suspendisse potenti. Phasellus feugiat tellus
        at tortor lacinia, a posuere est hendrerit. Integer fermentum mi non
        augue scelerisque, eu vehicula dui eleifend. Fusce tristique, justo at
        varius sagittis, ante nisi dictum libero, eget sodales quam purus quis
        ex. Quisque tristique augue id odio tristique, nec facilisis justo
        fermentum. Sed non viverra urna, eget vulputate urna. Vivamus at risus
        ac nisi iaculis hendrerit. Nulla facilisi. Suspendisse potenti.
      </div>
    </main>
  );
}
