import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import styles from '../app/components/NavBar.module.scss';
import Footer from './components/Footer';
import NavBar from './components/NavBar';
import SearchBar from './components/SearchBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home Page | Bliss', template: '%s Bliss' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.navigationBar}>
          <NavBar />

          {/* <div className={styles.logoContainer}>
            <Link href="/#">
              <Image className="{styles.logo}" src={logo} alt="bliss logo" />
            </Link>
          </div> */}

          <Footer />
        </div>
        <div className={styles.cartContainer}>
          <SearchBar />
          {children}
        </div>
      </body>
    </html>
  );
}

// for all pages

// <nav>
//           <div>
//             <Link href="/home">Home</Link>
//             <Link href="/products">Products</Link>
//             <Link href="/about">About Us</Link>
//           </div>
//           {Math.floor(Math.random() * 10)}
//         </nav>
