import Image from 'next/image';
import Link from 'next/link';
import { getProducts } from '../../database/products';

export const metadata = {
  title: 'Products Page',
  description: 'Generated by create next app',
};

export default function ProductsPage() {
  const products = getProducts();
  return (
    <div>
      <h1>These are my products</h1>

      {products.map((product) => {
        return (
          <div key={`product-div-${product.id}`}>
            <Link href={`/products/${product.id}`}>{product.firstName}</Link>
            <h1>{product.firstName}</h1>
            <Image
              src={`/images/${product.firstName}.jpeg`}
              alt={product.firstName}
              width={200}
              height={200}
            />
          </div>
        );
      })}
    </div>
  );
}
