import Image from 'next/image';
import Link from 'next/link';
import { getProducts } from '../../database/products';

export const metadata = {
  title: 'Bliss | Products',
  description: 'Generated by create next app',
};

// export type CookieQuantityItem = {
//   id: number;
//   quantity: number;
// };

// type Props = {
//   params: { productId: string }; // string because product id is in url
// };

export default async function ProductsPage() {
  const products = await getProducts();

  // console.log (
  // getallProductsFromDatabase().then((product) => console.log(product)),
  // );
  return (
    <div>
      <h1>Products</h1>

      {products.map((product) => {
        return (
          <div key={`product-div-${product.id}`}>
            <Link href={`/products/${product.id}`}>{product.name}</Link>
            <Image
              src={`/images/${product.name}.jpeg`}
              alt={product.name}
              width={200}
              height={200}
            />
          </div>
        );
      })}
    </div>
  );
}
